<a href="https://colab.research.google.com/github/ourdigital/our-gbp-toolkit/blob/main/Data%20Analysis/Level%201/Pandas_for_Data_Analysis_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas for Data Analysis
This notebook provides a beginner-friendly walkthrough of key pandas functionalities using simple examples. Topics include:
- Reading data from CSV, Excel, and JSON
- Selecting and filtering rows and columns
- Merging, joining, and concatenating datasets
- Grouping and aggregating data
- Applying functions with `.apply()`, `.map()`, and `.lambda`
- Transforming data with `.pivot()`, `.melt()`, `.stack()`, `.unstack()`

In [1]:
# Importing required libraries
import pandas as pd
import numpy as np
import json

## Reading Data
We'll create small example files and read them using pandas.

In [2]:
# Read CSV
df_csv = pd.read_csv('/content/JHR-IG-All-Adset-20260406.csv')
df_csv

,광고 이름,연령,광고,목표,행동 유도,광고 게재,도달,노출,빈도,결과 유형,...,결과당 비용,지출 금액 (KRW),시작,종료,"CPM(1,000회 노출당 비용)",링크 클릭,CPC(링크 클릭당 비용),CTR(링크 클릭률),보고 시작,보고 종료
0,NaN,NaN,NaN,NaN,NaN,NaN,1226491,3550315,2.894693,NaN,...,NaN,17039215,NaN,NaN,4799.353015,61310.0,277.919018,1.726889,2026-01-01,2026-04-06
1,IG_트래픽_JHR_2026 랜쇼페 티징_20260323,35-44,IG_트래픽_JHR_2026 랜쇼페 티징_20260323,LINK_CLICKS,LEARN_MORE,inactive,26649,37629,1.412023,링크 클릭,...,207.238994,230657,2026-03-23,2026-03-31,6129.766935,1113.0,207.238994,2.957825,2026-01-01,2026-04-06
2,IG_트래픽_JHR_2026 랜쇼페 티징_20260323,35-44,IG_트래픽_JHR_2026 랜쇼페 티징_20260323,LINK_CLICKS,LEARN_MORE,inactive,42731,62614,1.465306,링크 클릭,...,143.472065,228551,2026-03-23,2026-03-31,3650.158112,1593.0,143.472065,2.544159,2026-01-01,2026-04-06
3,IG_트래픽_JHR_2026 랜쇼페 티징_20260323,25-34,IG_트래픽_JHR_2026 랜쇼페 티징_20260323,LINK_CLICKS,LEARN_MORE,inactive,28257,39447,1.396008,링크 클릭,...,228.179518,189389,2026-03-23,2026-03-31,4801.100210,830.0,228.179518,2.104089,2026-01-01,2026-04-06
4,IG_트래픽_JHR_2026 랜쇼페 티징_20260323,25-34,IG_트래픽_JHR_2026 랜쇼페 티징_20260323,LINK_CLICKS,LEARN_MORE,inactive,39095,58262,1.490267,링크 클릭,...,153.325602,171878,2026-03-23,2026-03-31,2950.087536,1121.0,153.325602,1.924067,2026-01-01,2026-04-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,IG_트래픽_WJB_2026 랜쇼페 식음_20260401,Unknown,IG_트래픽_WJB_2026 랜쇼페 식음_20260401,LINK_CLICKS,BOOK_TRAVEL,active,1,1,1.000000,링크 클릭,...,NaN,10,2026-04-01,2026-04-12,10000.000000,NaN,NaN,NaN,2026-01-01,2026-04-06
150,IG_트래픽_JHR_2026 랜쇼페 티징_20260323,Unknown,IG_트래픽_JHR_2026 랜쇼페 티징_20260323,LINK_CLICKS,LEARN_MORE,inactive,2,2,1.000000,링크 클릭,...,NaN,4,2026-03-23,2026-03-31,2000.000000,NaN,NaN,NaN,2026-01-01,2026-04-06
151,IG_트래픽_GJJ_2026 랜쇼페 식음_20260401,Unknown,IG_트래픽_GJJ_2026 랜쇼페 식음_20260401,LINK_CLICKS,BOOK_TRAVEL,active,1,1,1.000000,링크 클릭,...,3.000000,3,2026-04-01,2026-04-12,3000.000000,1.0,3.000000,100.000000,2026-01-01,2026-04-06
152,IG_트래픽_GJB_2026 랜쇼페 식음_20260401,Unknown,IG_트래픽_GJB_2026 랜쇼페 식음_20260401,LINK_CLICKS,BOOK_TRAVEL,active,1,1,1.000000,링크 클릭,...,NaN,3,2026-04-01,2026-04-12,3000.000000,NaN,NaN,NaN,2026-01-01,2026-04-06
153,IG_트래픽_JHR_2026 랜쇼페 연회_20260401,Unknown,IG_트래픽_JHR_2026 랜쇼페 연회_20260401,LINK_CLICKS,LEARN_MORE,active,1,1,1.000000,링크 클릭,...,NaN,3,2026-04-01,2026-04-12,3000.000000,NaN,NaN,NaN,2026-01-01,2026-04-06

In [3]:
df_csv = df_csv.drop(df_csv.index[0])
display(df_csv.head())

,광고 이름,연령,광고,목표,행동 유도,광고 게재,도달,노출,빈도,결과 유형,...,결과당 비용,지출 금액 (KRW),시작,종료,"CPM(1,000회 노출당 비용)",링크 클릭,CPC(링크 클릭당 비용),CTR(링크 클릭률),보고 시작,보고 종료
1,IG_트래픽_JHR_2026 랜쇼페 티징_20260323,35-44,IG_트래픽_JHR_2026 랜쇼페 티징_20260323,LINK_CLICKS,LEARN_MORE,inactive,26649,37629,1.412023,링크 클릭,...,207.238994,230657,2026-03-23,2026-03-31,6129.766935,1113.0,207.238994,2.957825,2026-01-01,2026-04-06
2,IG_트래픽_JHR_2026 랜쇼페 티징_20260323,35-44,IG_트래픽_JHR_2026 랜쇼페 티징_20260323,LINK_CLICKS,LEARN_MORE,inactive,42731,62614,1.465306,링크 클릭,...,143.472065,228551,2026-03-23,2026-03-31,3650.158112,1593.0,143.472065,2.544159,2026-01-01,2026-04-06
3,IG_트래픽_JHR_2026 랜쇼페 티징_20260323,25-34,IG_트래픽_JHR_2026 랜쇼페 티징_20260323,LINK_CLICKS,LEARN_MORE,inactive,28257,39447,1.396008,링크 클릭,...,228.179518,189389,2026-03-23,2026-03-31,4801.100210,830.0,228.179518,2.104089,2026-01-01,2026-04-06
4,IG_트래픽_JHR_2026 랜쇼페 티징_20260323,25-34,IG_트래픽_JHR_2026 랜쇼페 티징_20260323,LINK_CLICKS,LEARN_MORE,inactive,39095,58262,1.490267,링크 클릭,...,153.325602,171878,2026-03-23,2026-03-31,2950.087536,1121.0,153.325602,1.924067,2026-01-01,2026-04-06
5,IG_트래픽_GJJ_2026 랜쇼페 객실_20260401,35-44,IG_트래픽_GJJ_2026 랜쇼페 객실_20260401,LINK_CLICKS,BOOK_TRAVEL,active,13781,22296,1.617880,링크 클릭,...,80.081621,140303,2026-04-01,2026-04-12,6292.743093,1752.0,80.081621,7.857912,2026-01-01,2026-04-06